# Generated by Django 4.2.29 on 2026-04-05 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPUCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cloud",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon Web Services"),
                            ("gcp", "Google Cloud Platform"),
                            ("azure", "Microsoft Azure"),
                            ("coreweave", "CoreWeave"),
                            ("lambda", "Lambda Labs"),
                            ("on_prem", "On-Premises"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                (
                    "k8s_context",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="kubectl context name for this cluster",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_orgs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "cost_center",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Billing / chargeback cost center identifier",
                        max_length=100,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="monitor.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="InferenceEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(help_text="Metrics endpoint URL", max_length=500),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("vllm", "vLLM"),
                            ("tgi", "Text Generation Inference"),
                            ("triton", "Triton Inference Server"),
                            ("trt-llm", "TensorRT-LLM"),
                            ("custom", "Custom"),
                        ],
                        default="vllm",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_endpoints",
                        to="monitor.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GPUNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                (
                    "instance_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cloud instance type, e.g. p4d.24xlarge",
                        max_length=100,
                    ),
                ),
                ("gpu_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "gpu_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GPU model string, e.g. NVIDIA A100-SXM4-80GB",
                        max_length=200,
                    ),
                ),
                (
                    "gpu_memory_gb",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "hourly_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="$/hr for the entire node (from cloud pricing or user override)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "k8s_node_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("k8s_labels", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("degraded", "Degraded"),
                            ("offline", "Offline"),
                            ("draining", "Draining"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "agent_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="monitor.gpucluster",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpu_nodes",
                        to="monitor.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddField(
            model_name="gpucluster",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gpu_clusters",
                to="monitor.organization",
            ),
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gpu_index",
                    models.SmallIntegerField(
                        help_text="nvidia-smi device index (0, 1, 2, ...)"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        help_text="NVIDIA GPU UUID (GPU-xxxxxxxx-xxxx-...)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "current_utilization",
                    models.FloatField(
                        blank=True, help_text="GPU utilization % (0-100)", null=True
                    ),
                ),
                ("current_memory_used_mb", models.IntegerField(blank=True, null=True)),
                ("current_memory_total_mb", models.IntegerField(blank=True, null=True)),
                (
                    "current_temperature_c",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("current_power_watts", models.FloatField(blank=True, null=True)),
                ("current_clock_mhz", models.IntegerField(blank=True, null=True)),
                (
                    "current_model_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "current_k8s_pod",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unreachable", "Unreachable"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("ecc_errors", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "current_endpoint_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_gpus",
                        to="monitor.inferenceendpoint",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpus",
                        to="monitor.gpunode",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpus",
                        to="monitor.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["node", "gpu_index"],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "key_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("key_prefix", models.CharField(max_length=8)),
                ("scopes", models.JSONField(default=list)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="monitor.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("operator", "Operator"),
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                        ],
                        default="viewer",
                        max_length=10,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="monitor.organization",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="monitor.team",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "role"],
                        name="monitor_use_organiz_61b3b6_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["organization"], name="monitor_tea_organiz_53c3ca_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["owner"], name="monitor_org_owner_i_9f81d0_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["plan"], name="monitor_org_plan_dcf342_idx"),
        ),
        migrations.AddIndex(
            model_name="inferenceendpoint",
            index=models.Index(
                fields=["organization", "is_active"],
                name="monitor_inf_organiz_2b21dc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inferenceendpoint",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="gpunode",
            index=models.Index(
                fields=["organization", "status"], name="monitor_gpu_organiz_156b45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpunode",
            index=models.Index(
                fields=["cluster", "hostname"], name="monitor_gpu_cluster_2f092e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gpunode",
            unique_together={("organization", "hostname")},
        ),
        migrations.AddIndex(
            model_name="gpucluster",
            index=models.Index(
                fields=["organization", "cloud"], name="monitor_gpu_organiz_f3f760_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gpucluster",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="gpu",
            index=models.Index(
                fields=["organization", "status"], name="monitor_gpu_organiz_ca4060_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpu",
            index=models.Index(
                fields=["node", "status"], name="monitor_gpu_node_id_158f98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpu",
            index=models.Index(fields=["uuid"], name="monitor_gpu_uuid_a7c31a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gpu",
            unique_together={("node", "gpu_index")},
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["organization", "active"], name="monitor_api_organiz_82dba4_idx"
            ),
        ),
    ]
