# Generated by Django 4.2.29 on 2026-04-05 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_cost_hypertable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("context", models.JSONField(default=dict)),
                ("notification_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("gpu_utilization_low", "GPU Underutilization"),
                            ("gpu_memory_high", "GPU Memory High"),
                            ("latency_high", "Latency High"),
                            ("gpu_offline", "GPU Offline"),
                            ("cost_anomaly", "Cost Anomaly"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        help_text="Trigger when metric exceeds (or falls below) this value"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="Metric must be out-of-bounds for this many seconds before firing",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("slack_webhook_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["organization", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="inferenceendpoint",
            name="framework",
        ),
        migrations.RemoveField(
            model_name="inferenceendpoint",
            name="last_scraped",
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_avg_latency_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_batch_utilization",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_kv_cache_usage_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_model",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_p99_latency_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_queue_depth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_requests_per_sec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="current_tokens_per_sec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="engine",
            field=models.CharField(
                choices=[
                    ("vllm", "vLLM"),
                    ("tgi", "Text Generation Inference"),
                    ("triton", "Triton Inference Server"),
                    ("ollama", "Ollama"),
                    ("custom", "Custom"),
                ],
                default="vllm",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="last_seen",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="max_batch_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="quantization",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="status",
            field=models.CharField(
                choices=[
                    ("serving", "Serving"),
                    ("loading", "Loading"),
                    ("idle", "Idle"),
                    ("error", "Error"),
                    ("offline", "Offline"),
                ],
                db_index=True,
                default="idle",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="inferenceendpoint",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inference_endpoints",
                to="monitor.team",
            ),
        ),
        migrations.AlterField(
            model_name="inferenceendpoint",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Metrics/API endpoint URL",
                max_length=500,
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceendpoint",
            index=models.Index(
                fields=["organization", "status"], name="monitor_inf_organiz_857aa6_idx"
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="monitor.organization",
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="monitor.alertrule",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["organization", "is_enabled"],
                name="monitor_ale_organiz_aa25e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["rule", "triggered_at"], name="monitor_ale_rule_id_79a6e1_idx"
            ),
        ),
    ]
