# Generated by Django 4.2.29 on 2026-04-06 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0008_invite_fixes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("anthropic", "Anthropic"), ("openai", "OpenAI")],
                        max_length=32,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human name, e.g. 'Production Key'", max_length=100
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(help_text="Fernet-encrypted API key"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_providers",
                        to="monitor.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Provider",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Calendar day (UTC) this record covers"),
                ),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=200)),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                ("cache_creation_tokens", models.BigIntegerField(default=0)),
                ("cache_read_tokens", models.BigIntegerField(default=0)),
                ("request_count", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage_records",
                        to="monitor.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Usage Record",
                "ordering": ["-date", "provider", "model"],
                "unique_together": {("date", "organization", "provider", "model")},
            },
        ),
    ]
