# Generated by Django 4.2.29 on 2026-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0009_llm_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="llmprovider",
            index=models.Index(
                fields=["organization", "is_active"],
                name="monitor_llm_organiz_32dadf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagerecord",
            index=models.Index(
                fields=["organization", "date"], name="monitor_llm_organiz_0253d4_idx"
            ),
        ),
    ]
